name: xbox_launcher
description: XCloud with the Xbox Series S/X's interface.
version: 0.0.3

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  fluent_ui: ^4.2.0
  webview_windows: ^0.2.2
  provider: ^6.0.5
  xinput_gamepad: ^1.2.3
  virtual_keyboard:
    git: https://github.com/LuanRoger/virtual_keyboard
  clock: ^1.1.1
  window_manager: ^0.3.0
  shared_preferences: ^2.0.15
  file_picker: ^5.2.5
  sprintf: ^7.0.0
  carousel_slider: ^4.2.1
  path_provider: ^2.0.11
  flutter_svg: ^1.1.6
  sys_info_getter:
    path: ./internals/sys_info_getter/
  url_launcher: ^6.1.7
  path: ^1.8.2
  fluentui_system_icons: ^1.1.190

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0
  msix: ^3.7.0

msix_config:
  display_name: Xbox Launcher
  publisher_display_name: Luan Roger
  identity_name: luanroger.xboxlauncher
  msix_version: 0.0.3.0
  capabilities: internetClient
  enable_at_startup: false
  output_name: xbox_launcher
  store: false
  architecture: x64
  publisher: CN=Luan Roger, C=BR
  sign_msix: false

flutter:
  uses-material-design: true

  assets:
  - assets/buttons/
  - assets/svgs/

  fonts:
    - family: Bahnschrift
      fonts:
        - asset: assets/fonts/Bahnschrift/Bahnschrift.ttf
    - family: Segoe
      fonts:
        - asset: assets/fonts/Segoe/SegoeUI.ttf
        - asset: assets/fonts/Segoe/SegoeUIItalic.ttf
          style: italic
        - asset: assets/fonts/Segoe/SegoeUIBold.ttf
          weight: 700
        - asset: assets/fonts/Segoe/SegoeUIBoldItalic.ttf
          weight: 700
          style: italic