name: xbox_launcher
description: XCloud with the Xbox Series S/X's interface.
version: 0.0.1

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  fluent_ui: ^3.12.0
  webview_windows: ^0.2.1
  provider: ^6.0.3
  xinput_gamepad: ^1.1.0
  virtual_keyboard:
    git: https://github.com/LuanRoger/virtual_keyboard.git
  clock: ^1.1.1
  window_manager: ^0.2.7
  shared_preferences: ^2.0.15
  file_picker: ^5.0.1
  sprintf: ^6.0.2
  carousel_slider: ^4.1.1
  path_provider: ^2.0.11
  win32: ^2.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

  assets:
  - assets/buttons/

  fonts:
    - family: Bahnschrift
      fonts:
        - asset: assets/fonts/Bahnschrift/Bahnschrift.ttf
    - family: Segoe
      fonts:
        - asset: assets/fonts/Segoe/SegoeUI.ttf
        - asset: assets/fonts/Segoe/SegoeUIItalic.ttf
          style: italic
        - asset: assets/fonts/Segoe/SegoeUIBold.ttf
          weight: 700
        - asset: assets/fonts/Segoe/SegoeUIBoldItalic.ttf
          weight: 700
          style: italic